[package]
name = "game-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
game-types = { path = "../../shared/game-types" }
glam = { workspace = true }
libm = "0.2"

[features]
default = []
