[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "-C", "link-arg=-Tkernel/linker-x86_64.ld",
    "-C", "relocation-model=static",
    "-C", "code-model=kernel",
]

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]
